version: '3'

services:

  webapp:
    build:
      context: ../../webapp
      dockerfile: Dockerfile.dev
    volumes:
      - ../../webapp/src:/app/src
      - ../../webapp/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - claimclam_net

  gateway:
    image: cosmtrek/air
    working_dir: /claimclam
    entrypoint: ["air", "-c", "./services/gateway/air.toml"]
    volumes:
      - ../..:/claimclam:delegated
    ports:
      - 3001:3001
    environment:
      PORT: 3001
    env_file:
      - ../../.env
    networks:
      - claimclam_net

networks:
  claimclam_net: