package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"

	"github.com/mamalovesyou/getclaim/graphql/gen/model"
	"github.com/mamalovesyou/getclaim/internal/logging"
	"github.com/mamalovesyou/getclaim/internal/podcasts"
	"github.com/mamalovesyou/getclaim/services/gateway/graph"
)

// Podcasts is the resolver for the podcasts field.
func (r *queryResolver) Podcasts(ctx context.Context, search *string, title *string, categoryName *string, page *int, limit *int) ([]*model.Podcast, error) {
	logging.WithContext(ctx).Debug("Podcast query")
	params := &podcasts.ListPodcastsParams{
		Search:       search,
		Title:        title,
		CategoryName: categoryName,
		Page:         page,
		Limit:        limit,
	}
	return r.podcastsClient.ListPodcasts(ctx, params)
}

// Query returns graph1.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
