package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"
	"fmt"

	"github.com/mamalovesyou/getclaim/graphql/gen/model"
	graph1 "github.com/mamalovesyou/getclaim/services/gateway/graph"
)

// Podcasts is the resolver for the podcasts field.
func (r *queryResolver) Podcasts(ctx context.Context, search *string, title *string, categoryName *string, page *int, limit *int) ([]*model.Podcast, error) {
	panic(fmt.Errorf("not implemented: Podcasts - podcasts"))
}

// Query returns graph1.QueryResolver implementation.
func (r *Resolver) Query() graph1.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
